### ISSUE TITLE
i was very appraciated if you would give me some help!!! 

### ISSUE THREAD

**Issue by NBJY688** [icsl-Jeon/dual_chaser#3]
Hi,Thanks for your so wonderful work.But i have a problem with the code .I have configured the environment according your "README", when i launch the file,some warning appears like"TargetManager: target_0_filtered not found. We use position of the tf for prediction." .Also there is some error like " Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees."     The it appears nothing in rviz.i have spent days to solve this problem. can you give me some advice.Thank you so much

**Comment by icsl-Jeon** [comment]
Thank you for using the library.
It means the '/tf' did not include the described frame of the target! 
Your tf have to provide the frame of the target to be followed. Can you provide the tf tree?

**Comment by NBJY688** [comment]
yeah, of course, i did not use real target,just use the bag.Here is the tf tre
[frames.pdf](https://github.com/icsl-Jeon/dual_chaser/files/7791479/frames.pdf)
e

**Comment by NBJY688** [comment]
Thanks for your replay!!

**Comment by icsl-Jeon** [comment]
Please change the below     
`<arg name= "is_bag" default = "false"/>`
    
Intro 
`<arg name= "is_bag" default = "true"/>`

**Comment by NBJY688** [comment]
i have tried but i did not work.i am going to give up....

**Comment by icsl-Jeon** [comment]
Would you please to wait a little bit?
I will check until tomorrow. Let me contract you here if somethings are found. 
Thank you.

**Comment by NBJY688** [comment]
Yes!of course.I'm just afraid to disturb you.I look forward to your reply.Thanks so much.

**Comment by icsl-Jeon** [comment]
Thank you for your patience. 
Did you down load a bag file on the [link](https://drive.google.com/drive/folders/1AtZIgeRLxQMqIC9SMKBOhj9OXK96uEfw)
and specify its file in the launch file (such as `/home/jbs/Downloads/forest1.bag` in the below)?  
```
    <include file="$(find zed2_client)/launch/client.launch">
        <arg name="is_bag" value="$(arg is_bag)"/>
        <arg name="bag_file" value="/home/jbs/Downloads/forest1.bag"/>  
```

**Comment by NBJY688** [comment]
Hi,i am so appreciated of your reply.But indeed i have done this before i give this issue.i does not work.Maybe i think whether it because my ubuntu version:18.04 not 20.04.can you give me some advice if i use ubuntu 18.04 for this code.Thanks very much.
