### ISSUE TITLE
something about "VisibilityScoreField::traverse"

### ISSUE THREAD

**Issue by NBJY688** [icsl-Jeon/dual_chaser#4]
Hi, very appreciate your wonderful work and i'm learning your code .But could you tell me the the intention of "VisibilityScoreField::traverse".   I can not understand it clearly.
Thanks very much.

**Comment by icsl-Jeon** [comment]
Were you able to run the code? You issued that the bag file could not run :(
The code is an implementation of FIGURE 8 of my paper. !

**Comment by icsl-Jeon** [comment]
Refer my paper: 
https://ieeexplore.ieee.org/abstract/document/9557293/

**Comment by NBJY688** [comment]
Thanks so much ! i will read it carefully.  And one last problem.can repo"traj_gen_vis_deprecated" still work?if can,could you give me some advice about how configure this repo.

**Comment by icsl-Jeon** [comment]
I am sorry, but the repo is not runnable. Closing this issue.
