### ISSUE TITLE
[ERROR]TargetManager: prediction not available. Ensure all targets received pose from tf

### ISSUE THREAD

**Issue by nixwang** [icsl-Jeon/dual_chaser#6]
Hello, thanks for the open source code. 
When I run the code `roslaunch dual_chaser zed_online.launch is_bag:=true`, it is error as below.

`[ERROR] [1680752775.723689867, 1624257010.859834965]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.723697561, 1624257010.859834965]: Wrapper: prediction failed
[ERROR] [1680752775.723703496, 1624257010.859834965]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752775.763856672, 1624257010.900345732]: TargetManager: prediction too old 1624257010.900346. need new prediction.
[ INFO] [1680752775.763878656, 1624257010.900345732]: Wrapper: trigger planning
[ERROR] [1680752775.763900728, 1624257010.900345732]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.763909166, 1624257010.900345732]: Wrapper: prediction failed
[ERROR] [1680752775.763915505, 1624257010.900345732]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752775.804140719, 1624257010.940795931]: TargetManager: prediction too old 1624257010.940796. need new prediction.
[ INFO] [1680752775.804162942, 1624257010.940795931]: Wrapper: trigger planning
[ERROR] [1680752775.804177474, 1624257010.940795931]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.804192872, 1624257010.940795931]: Wrapper: prediction failed
[ERROR] [1680752775.804206827, 1624257010.940795931]: Wrapper: planning failed. will trigger new..
[ WARN] [1680752775.824458306, 1624257010.960997160]: TargetManager: target_0_filtered not found. We use position of the tf for prediction.
[ WARN] [1680752775.824482242, 1624257010.960997160]: Target tf (target_0_filtered) is not updated for 1624257024.000000 s
[ WARN] [1680752775.824499584, 1624257010.960997160]: TargetManager: target_1_filtered not found. We use position of the tf for prediction.
[ WARN] [1680752775.824524334, 1624257010.960997160]: Target tf (target_1_filtered) is not updated for 1624257024.000000 s
[ INFO] [1680752775.845383321, 1624257010.981148763]: TargetManager: prediction too old 1624257010.981149. need new prediction.
[ INFO] [1680752775.845402757, 1624257010.981148763]: Wrapper: trigger planning
[ERROR] [1680752775.845413052, 1624257010.981148763]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.845437225, 1624257010.981148763]: Wrapper: prediction failed
[ERROR] [1680752775.845443093, 1624257010.981148763]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752775.885542421, 1624257011.021557033]: TargetManager: prediction too old 1624257011.021557. need new prediction.
[ INFO] [1680752775.885568440, 1624257011.021557033]: Wrapper: trigger planning
[ERROR] [1680752775.885595190, 1624257011.021557033]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.885602266, 1624257011.021557033]: Wrapper: prediction failed
[ERROR] [1680752775.885609280, 1624257011.021557033]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752775.925118642, 1624257011.061767714]: TargetManager: prediction too old 1624257011.061768. need new prediction.
[ INFO] [1680752775.925141608, 1624257011.061767714]: Wrapper: trigger planning
[ERROR] [1680752775.925152858, 1624257011.061767714]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.925163992, 1624257011.061767714]: Wrapper: prediction failed
[ERROR] [1680752775.925172834, 1624257011.061767714]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752775.965535499, 1624257011.102218811]: TargetManager: prediction too old 1624257011.102219. need new prediction.
[ INFO] [1680752775.965552507, 1624257011.102218811]: Wrapper: trigger planning
[ERROR] [1680752775.965565193, 1624257011.102218811]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752775.965574080, 1624257011.102218811]: Wrapper: prediction failed
[ERROR] [1680752775.965582607, 1624257011.102218811]: Wrapper: planning failed. will trigger new..
^C[ INFO] [1680752776.006610231, 1624257011.142775174]: TargetManager: prediction too old 1624257011.142775. need new prediction.
[ INFO] [1680752776.006648683, 1624257011.142775174]: Wrapper: trigger planning
[ERROR] [1680752776.006662020, 1624257011.142775174]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752776.006671523, 1624257011.142775174]: Wrapper: prediction failed
[ERROR] [1680752776.006683012, 1624257011.142775174]: Wrapper: planning failed. will trigger new..
[ WARN] [1680752776.026924887, 1624257011.163002658]: TargetManager: target_0_filtered not found. We use position of the tf for prediction.
[ WARN] [1680752776.026946181, 1624257011.163002658]: Target tf (target_0_filtered) is not updated for 1624257024.000000 s
[ WARN] [1680752776.026981706, 1624257011.163002658]: TargetManager: target_1_filtered not found. We use position of the tf for prediction.
[ WARN] [1680752776.026991444, 1624257011.163002658]: Target tf (target_1_filtered) is not updated for 1624257024.000000 s
[ INFO] [1680752776.046857168, 1624257011.183255818]: TargetManager: prediction too old 1624257011.183256. need new prediction.
[ INFO] [1680752776.046877533, 1624257011.183255818]: Wrapper: trigger planning
[ERROR] [1680752776.046893429, 1624257011.183255818]: TargetManager: prediction not available. Ensure all targets received pose from tf
[ERROR] [1680752776.046904299, 1624257011.183255818]: Wrapper: prediction failed
[ERROR] [1680752776.046914250, 1624257011.183255818]: Wrapper: planning failed. will trigger new..
[ INFO] [1680752776.087047020, 1624257011.223636590]: TargetManager: prediction too old 1624257011.223637. need new prediction.
[ INFO] [1680752776.087066824, 1624257011.223636590]: Wrapper: trigger planning
`

Is there any suggestion for this problem?

**Comment by nixwang** [comment]
need change the "target_frame_set" in target_manager.launch and run.launch. e.g. target_0_filtered -> bag_target_0_filtered

**Comment by ltf1001** [comment]
Hello, thank you very much for sharing.
I also encountered this problem, but according to your solution, I can't solve it. Can you tell me the specific code configuration?

**Comment by ltf1001** [comment]
I have solved this issue, thank you very much for sharing.
