### ISSUE TITLE
Trajectory predict wrong

### ISSUE THREAD

**Issue by nixwang** [icsl-Jeon/dual_chaser#7]
Hello, thanks for the open source code.
As shown in below picture, the targets moves as the thin red and blue line. While the predicted trajectories are not along with the motion trajectory, but perpendicular to the motion direction.  The target_lib_name is target2d_2s.
![rviz_screenshot_2023_06_30-16_54_09](https://github.com/icsl-Jeon/dual_chaser/assets/26763294/116c03be-4b99-4549-8474-5c0addec24a3)

**Comment by nixwang** [comment]
Is there any suggestion for this problem? Thanks

**Comment by icsl-Jeon** [comment]
Thank you for having an interest in this repo!
My suggestion is: you'd better check the observations of the targets which are published in the topic of `observation_keyframe` .
I think the horizon used for gathering observation is too short, leading to bad prediction.

**Comment by nixwang** [comment]
Thanks for your reply.
![Screenshot from 2023-06-30 21-57-47](https://github.com/icsl-Jeon/dual_chaser/assets/26763294/c14d6fc5-92e2-4524-90f8-def4c8ad3560)
The observations of the targets  seems good. And I use horizon to 5s,  the prediction is still not so reasonable.

**Comment by icsl-Jeon** [comment]
Are you providing reasonable tf for targets? especially for direction :)

**Comment by nixwang** [comment]
Oh!! Thanks for your kind remind. It's really the problem of the direction of the targets. Wonderful!

**Comment by icsl-Jeon** [comment]
Awesome! Please recommend my code to your colleagues if it helped you! 
Have a nice day :)

**Comment by nixwang** [comment]
No problem. It's my pleasure to share such a perfect project.
